### ISSUE TITLE
TOPページで登壇者をクリックしたら、その登壇者の代表的なセッション詳細に飛ぶ

### ISSUE THREAD

**Issue by fullvirtue** [fullvirtue/sendaiitfes-tools#6]
* speakers.ymlの台帳に、セッション詳細へのリンクを入れる列を追加
* 台帳を整備
* URLがあればリンクを貼る
* URLがなければリンクは貼らない

**Comment by hiroyukimori** [comment]
スピーカー情報にDirectLinkフィールドを追加し、該当フィールドに入力があればリンクを出力するよう修正します。
